###
//CADASTRAR
POST https://localhost:5001/api/produto/create
Content-Type: application/json

{
    "Nome" : "bolachass",
    "Preco" : 4.5
}

###
//LISTAR
GET  https://localhost:5001/api/produto/list
Content-Type: application/json

###
//EXCLUIR POR ID
POST https://localhost:5001/api/produto/delete 
Content-Type: application/json

{
    "Id" : 1 
}

###
//EXCLUIR POR NOME
POST https://localhost:5001/api/produto/delete 
Content-Type: application/json

{
    "Nome" : "bolachass" 
}

###
//ALTERAR
POST https://localhost:5001/api/produto/update
Content-Type: application/json

{
    "Id" : 3, 
    "Nome" : "Caio",
    "Descricao" : "Have fun, Dont die"
}

###
//Busca por Id
GET https://localhost:5001/api/produto/getbyid/3
